### ISSUE TITLE
Add first and last active fields to wallet view

### ISSUE THREAD

**Issue by thedarkspy** [cibr-qcri/toshi#58]
- Add last active items to the results (date of last tx).
- update wallet summery API endpoint to include last and first active (timestamp of first and last tx of any of the wallet's addresses).
- In the wallet view, add first and last active to the summery

**Comment by boshmaf** [comment]
Calculating first/last seen for 20 wallets (search result) took more than 2 mins, so it's not going to work for real-time queries. We need to figure out a more efficient way to compute these values.

Pre-computing is one possible way. However, it might take more than a week to compute and update the table (btc_wallet) from (btc_wallet_transaction), as there are 100s of millions of records (and expensive join operations).
