### ISSUE TITLE
Missing wallet links

### ISSUE THREAD

**Issue by sajithaliyanage** [cibr-qcri/toshi#71]
**Describe the bug**
Visit this wallet, there is a transaction in which BTC goes to another wallet but that link is missing in the Link wallets tab, and top links views

**Comment by boshmaf** [comment]
Please add the example here! Without a way to replicate it's difficult to debug

**Comment by boshmaf** [comment]
Here you go: https://toshi.cibr.qcri.org/wallet/6bbe912a-4dfd-44c2-bdb4-f1cf72b520fb

**Comment by sajithaliyanage** [comment]
Related commit: https://github.com/cibr-qcri/airflow-tasks/commit/e3db92a3b7e6ec300564782a4f661d94f23a333b
