### ISSUE TITLE
BTC balance shows negative value

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/toshi#78]
**Describe the bug**
For some wallets, the btc balance shows a negative value.

**To Reproduce**
1. Go to [here](https://toshi.cibr.qcri.org/wallet/2c538964-99bd-4242-9a90-9ace7482f3f6)
2. See error

**Expected behavior**
The balance in btc should never be negative. Addresses in a wallet cannot spend more than they receive.

**Screenshots**
<img width="944" alt="Screen Shot 2022-06-06 at 3 33 50 PM" src="https://user-images.githubusercontent.com/3311191/172161510-bfcc6d03-1784-4385-9820-8e0cc274a639.png">

**Comment by sajithaliyanage** [comment]
According to the new clustering data, this wallet has been merged with another cluster 4d031741-8ea5-4913-b13a-8917a42b48dc. The new wallet has a positive balance. [See](https://toshi.cibr.qcri.org/wallet/2c538964-99bd-4242-9a90-9ace7482f3f6)
